# Change these first
owner: pfadfinden-bayern # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Cloud
    url: https://cloud.pfadfindenby.de
  - name: Wiki
    url: https://wiki.pfadfindenby.de
  - name: Login
    url: https://auth.pfadfindenby.de
  - name: Online-Office
    url: https://office.pfadfindenby.de

assignees:
  - jzbor

status-website:
  cname: status.pfadfindenby.de
  theme: night
  logoUrl: https://bayern.pfadfinden.de/_assets/d7ba28ebe12d82c738ecb5d8b9db3979/Build/Media/bundeszeichen-DXEtWgM-.svg
  name: BdP LV Bayern IT Status
  introTitle: "**Status** für die **IT-Dienste** des Landesverbandes Bayern im Bund der Pfadfinderinnen und Pfadfinder"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
